// AUTO-GENERATED by scripts/fetch-photos.mjs - local, verified photography.
// Slots absent from this map intentionally fall back to the SVG editorial artwork
// in lib/content/media.ts so no image slot can ever render empty.
export const PHOTO_MAP: Record<string, string> = {
  "hero-01": "/media/photos/hero-01.jpg",
  "hero-02": "/media/photos/hero-02.jpg",
  "hero-03": "/media/photos/hero-03.jpg",
  "laminate-flooring": "/media/photos/laminate-flooring.jpg",
  "spc-flooring": "/media/photos/spc-flooring.jpg",
  "vinyl-flooring": "/media/photos/vinyl-flooring.jpg",
  "wallpaper": "/media/photos/wallpaper.jpg",
  "folding-doors": "/media/photos/folding-door.jpg",
  "false-ceiling": "/media/photos/gypsum-false-ceiling.jpg",
  "window-blinds": "/media/photos/window-blinds.jpg",
  "pvc-wall-panels": "/media/photos/pvc-wall-panel.jpg",
  "3d-wall-picture": "/media/photos/3d-wall-picture.jpg",
  "artificial-grass": "/media/photos/artificial-grass.jpg",
  "work-featured": "/media/photos/work-featured.jpg",
  "work-02": "/media/photos/work-02.jpg",
  "work-03": "/media/photos/work-03.jpg",
  "philosophy": "/media/photos/philosophy.jpg",
  "services": "/media/photos/services.jpg",
  "og": "/media/photos/og.jpg"
};
