import fs from 'node:fs';
import path from 'node:path';
import https from 'node:https';
import sharp from 'sharp';

const OUT = 'public/media/photos';
fs.mkdirSync(OUT, { recursive: true });

const SLOTS = {
  'hero-01': ['1618221195710-dd6b41faaea6','1615873968403-89e068629265','1600210491892-03d54c0aaf87'],
  'hero-02': ['1615529182904-14819c35db37','1600607687939-ce8a6c25118c','1600585154340-be6161a56a0c'],
  'hero-03': ['1600210492486-724fe5c67fb0','1522708323590-d24dbb6b0267','1600566753086-00f18fb6b3ba'],
  'laminate-flooring': ['1581858726788-75bc0f6a952d','1600585154363-67eb9e2e2099','1513694203232-719a280e022f'],
  'spc-flooring': ['1600585154340-be6161a56a0c','1600607687920-4e2a09cf159d','1600566753190-17f0baa2a6c3'],
  'vinyl-flooring': ['1600702687568-24c221a2ca06','1600210491892-03d54c0aaf87','1522708323590-d24dbb6b0267'],
  'pvc-wall-panel': ['1616594039964-ae9081e00cf6','1616594266774-6089a8bfbbad','1602087562024-7e4f2e895c44'],
  'wallpaper': ['1604147706283-d7119b5b822c','1615873968403-89e068629265','1618374867641-4d47c0d95d5e'],
  'folding-door': ['1513694203232-719a280e022f','1600566753190-17f0baa2a6c3','1600607687939-ce8a6c25118c'],
  'gypsum-false-ceiling': ['1631679706909-1844bbd07221','1600607687920-4e2a09cf159d','1600585154363-67eb9e2e2099'],
  'window-blinds': ['1526628953301-3e589a6a8b74','1519710164239-da123dc03ef4','1505691938895-1758d7feb511'],
  '3d-wall-picture': ['1598300052391-95b2700aa998','1616594039964-ae9081e00cf6','1602087562024-7e4f2e895c44'],
  'artificial-grass': ['1558618666-fcd25c85cd64','1587302910309-9caa8e50e8c5','1523381210434-271e8be1f52b'],
  'work-featured': ['1600607687939-ce8a6c25118c','1600566753086-00f18fb6b3ba','1600585154340-be6161a56a0c'],
  'work-02': ['1600566752353-a3eeb7d6e16f','1600607687920-4e2a09cf159d','1522708323590-d24dbb6b0267'],
  'work-03': ['1600585154363-67eb9e2e2099','1600210492486-724fe5c67fb0','1615529182904-14819c35db37'],
  'philosophy': ['1600210492486-724fe5c67fb0','1615529182904-14819c35db37','1600210491892-03d54c0aaf87'],
  'services': ['1522708323590-d24dbb6b0267','1600566753190-17f0baa2a6c3','1600607687939-ce8a6c25118c'],
  'og': ['1618221195710-dd6b41faaea6','1600210492486-724fe5c67fb0']
};

function get(url, redirects = 0) {
  return new Promise((resolve, reject) => {
    if (redirects > 4) return reject(new Error('too many redirects'));
    https.get(url, { headers: { 'User-Agent': 'Mozilla/5.0' } }, (res) => {
      const st = res.statusCode || 0;
      if (st >= 300 && st < 400 && res.headers.location) {
        res.resume();
        return resolve(get(new URL(res.headers.location, url).toString(), redirects + 1));
      }
      if (st !== 200) { res.resume(); return reject(new Error('HTTP ' + st)); }
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks)));
      res.on('error', reject);
    }).on('error', reject);
  });
}

const chosen = {};
const failed = [];
for (const [slot, ids] of Object.entries(SLOTS)) {
  let done = false;
  for (const id of ids) {
    const w = slot.startsWith('hero') ? 1920 : (slot === 'og' ? 1200 : 1600);
    const url = 'https://images.unsplash.com/photo-' + id + '?w=' + w + '&q=80&auto=format&fit=crop';
    try {
      const buf = await get(url);
      if (buf.length < 40000) throw new Error('too small ' + buf.length + 'B');
      const meta = await sharp(buf, { failOn: 'none' }).metadata();
      if (!meta.width || meta.width < 600) throw new Error('too narrow');
      const out = await sharp(buf, { failOn: 'none' })
        .resize({ width: w, withoutEnlargement: true })
        .jpeg({ quality: 80, progressive: true, mozjpeg: true })
        .toBuffer();
      const file = slot + '.jpg';
      fs.writeFileSync(path.join(OUT, file), out);
      chosen[slot] = '/media/photos/' + file;
      console.log(slot, '<-', id, Math.round(out.length / 1024) + 'KB');
      done = true;
      break;
    } catch (e) {
      console.log(slot, 'skip', id, '-', String(e.message || e));
    }
  }
  if (!done) { failed.push(slot); console.log(slot, 'FAILED all candidates'); }
}

const ts = '// AUTO-GENERATED by scripts/fetch-photos.mjs - local, verified photography.\n// Slots absent from this map intentionally fall back to the SVG editorial artwork\n// in lib/content/media.ts so no image slot can ever render empty.\nexport const PHOTO_MAP: Record<string, string> = ' + JSON.stringify(chosen, null, 2) + ';\n';
fs.writeFileSync('lib/content/photo-map.ts', ts);
fs.writeFileSync(path.join(OUT, 'manifest.json'), JSON.stringify({ chosen, failed }, null, 2));
console.log('PHOTOS_DONE ok=' + Object.keys(chosen).length + ' failed=' + (failed.join(',') || 'none'));
if (failed.length) process.exit(1);
